baseURL = 'https://boyan.vercel.app/'
languageCode = 'en-us'
title = "Boyan's Blog"
theme = 'PaperMod'
enableGitInfo = true


[minify]
disableXML = true
minifyOutput = true

[frontmatter]

[params]
social = true
defaultTheme = 'auto'
author = "Boyan Xu"
hideAuthor = true

ShowReadingTime = true
ShowWordCount = true
