baseURL = 'https://boyanxu.com/'
languageCode = 'en-us'

title = "Boyan's Blog"
theme = 'PaperMod'
enableGitInfo = true


[minify]
disableXML = true
minifyOutput = true

[frontmatter]

[pagination]
pagerSize = 10

[params]
env = 'production'
title = "Boyan's Blog"
description = "Boyan's Blog"
keywords = ['Blog', 'Portfolio', 'PaperMod']
social = true
defaultTheme = 'auto'
DateFormat = "January 2, 2006"
author = "Boyan Xu"
image = "https://i.imgur.com/dDyM1tM.png"
hideAuthor = true
ShowReadingTime = true
ShowWordCount = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
hideSummary = false
showtoc = true
tocopen = true
socialIcons = [
    { name = "linkedin", url = "https://www.linkedin.com/in/boyan-xu-163818148/" },
    { name = "github", url = "https://github.com/BoyanXu" },
    { name = "email", url = "mailto:boyan.xu@requo.in" },
    { name = "Rss", url = "index.xml"},
    { name = "goodreads", url = "https://www.goodreads.com/boyanxu"},
    { name = "lastfm", url = "https://www.last.fm/user/boyanxu"},
    { name = "keybase", url = "https://keybase.io/boyan_xu"}
]


[params.assets]

favicon = "favicon/favicon.ico"
favicon16x16 = "favicon/favicon-16x16.png"
favicon32x32 = "favicon/favicon-32x32.png"
apple_touch_icon = "favicon/apple-touch-icon.png"
safari_pinned_tab = "favicon/favicon.ico"


[params.homeInfoParams]
Title = "Hi there, I'm Boyan. 👋"
Content = "Building a venture <a href='https://requo.in'>@Requo Inc</a>. Alumni of <a href='https://nyu.edu'>@NYU Tandon</a> and <a href='https://shanghai.nyu.edu/'>@NYU Shanghai</a>."


[markup.tableOfContents]
ordered = false
startLevel = 2
endLevel = 3
# Implementation assets/css/extended/toc-auto-numbering.css assume max level is 4



[markup.goldmark.extensions.cjk]
eastAsianLineBreaks = true
escapedSpace = true

[markup.goldmark.renderer]
unsafe = true
