baseURL = 'https://boyan.vercel.app/'
languageCode = 'en-us'
paginate = 10
title = "Boyan's Blog"
theme = 'PaperMod'
enableGitInfo = true


[minify]
disableXML = true
minifyOutput = true

[frontmatter]

[params]
env = 'production'
title = "Boyan's Blog"
keywords = ['Blog', 'Portfolio', 'PaperMod']
social = true
defaultTheme = 'auto'
author = "Boyan Xu"
image = "https://i.imgur.com/dDyM1tM.png"
hideAuthor = true
ShowReadingTime = true
ShowWordCount = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
hideSummary = false
showtoc = true
tocopen = true


[params.homeInfoParams]
Title = "Hi there, I'm Boyan. 👋"
Content = "I'm building a venture. Previously <a href='https://nyu.edu'>@NYU</a> Tandon and <a href='https://shanghai.nyu.edu/'>@NYU Shanghai</a>."


[markup.tableOfContents]
ordered = false
startLevel = 2
endLevel = 3



[markup.goldmark.extensions.cjk]
eastAsianLineBreaks = true
escapedSpace = true

[markup.goldmark.renderer]
unsafe = true
