baseURL = 'https://boyan.vercel.app/'
languageCode = 'en-us'
title = "Boyan's Blog"
theme = 'PaperMod'
enableGitInfo = true


[minify]
disableXML = true
minifyOutput = true

[params]
social = true
defaultTheme = 'auto'

[frontmatter]
