baseURL = 'https://boyan.vercel.app/'
languageCode = 'en-us'
title = "Boyan's Blog"
theme = 'PaperMod'
enableGitInfo = true


[minify]
disableXML = true
minifyOutput = true

[frontmatter]

[params]
social = true
defaultTheme = 'auto'
author = "Boyan Xu"
hideAuthor = true
ShowReadingTime = true
ShowWordCount = true

[params.homeInfoParams]
Title = "Hi there 👋"
Content = """
        <div>
            <p style="float: left; padding-right: 10px;">
                <img alt="emoji avatar of me" src="me_ar_sticker.webp" height="100px" width="100px">
            </p>
            <p>
                Everything technical gives me a lot of joy. Starting from <b>A</b> like <i>Artificial Intelligence</i> to <b>Z</b> like <i>Zener Diode</i> - I dig that stuff! 
                This blog is a collection of the thoughts, ideas, and projects that I would like to share with the world wide web.
            </p>
        </div>
        
        <div>
            <a href="https://github.com/dadul96">
                <p style="float: left; padding-top: 20px; padding-right: 15px;">
                    <img alt="github icon" src="github_icon.webp" width="32" height="32">
                </p>
            </a>
            <a href="mailto:daniel.duller@gmx.net">
                <p style="float: left; padding-top: 20px; padding-right: 15px;">
                    <img alt="email icon" src="email_icon.webp" width="32" height="32">
                </p>
            </a>
            <a href="https://www.thingiverse.com/dadul96/designs">
                <p style="float: left; padding-top: 20px; padding-right: 15px;">
                    <img alt="thingiverse icon" src="thingiverse_icon.webp" width="32" height="32">
                </p>
            </a>
            <a href="https://www.prusaprinters.org/social/192589-dadul96/about">
                <p style="float: left; padding-top: 20px; padding-right: 15px;">
                    <img alt="prusaprinters icon" src="prusaprinters_icon.webp" width="32" height="32">
                </p>
            </a>
            <a href="https://dadul96.github.io/index.xml">
                <p style="float: left; padding-top: 20px; padding-right: 15px;">
                    <img alt="rss icon" src="rss_icon.webp" width="32" height="32">
                </p>
            </a>
        </div>
"""

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.extensions.cjk]
eastAsianLineBreaks = true
eastAsianLineBreaksStyle = 'simple'
escapedSpace = false

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'

[markup.goldmark.parser.attribute]
block = false
title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
